### PR TITLE
Laravel 9 Support

### LINKED ISSUE #37: Laravel 9 support

### PR DESCRIPTION
**Pull request by RhysLees**

### CODE REVIEW

**Comment by llaski** [comment]
@RhysLees Laravel 9 now requires php 8.0 so need to add that to the versions of PHP to test - https://github.com/llaski/nova-scheduled-jobs/blob/master/.github/workflows/tests.yml#L14

**Comment by RhysLees** [comment]
> @RhysLees Laravel 9 now requires php 8.0 so need to add that to the versions of PHP to test - https://github.com/llaski/nova-scheduled-jobs/blob/master/.github/workflows/tests.yml#L14

complete oversight, my bad

**Comment by RhysLees** [comment]
Seems tests are failing due to invalid credentials or set up for the auto testing when getting nova?

Are you able to update this?

**Comment by llaski** [comment]
@RhysLees Unfortunately that issue is actually not fixable as GitHub does not allowed secrets to be shared for forked repos/PR's from forked repo's.

https://docs.github.com/en/actions/security-guides/encrypted-secrets
```
Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```

https://github.community/t/make-secrets-available-to-builds-of-forks/16166/21

However I have gone ahead and run the workflow separately and confirmed it works, so am merging this in. Thanks for your contribution!

Working Workflow: https://github.com/llaski/nova-scheduled-jobs/actions/runs/1850811938

**Comment by RhysLees** [comment]
Well that's annoying, hope they add something soon to solve this issue.

Thanks!

**Pull request merged**
