### PR TITLE
Nova 4 Compatibility

### PR DESCRIPTION
**Pull request by mertasan**

### CODE REVIEW

**Comment by repat** [comment]
@llaski could you merge this? The tests only fail because of the composer auth details

**Comment by llaski** [comment]
@repat Can you confirm the test suite is working on your local machine? I'm not able to run the tests as nova 4 requires a new license upgrade and currently don't have the new license yet. If you can confirm it works on your local machine with version 4 of nova I'll merge this in.

**Comment by mertasan** [comment]
@llaski 

> If you have purchased Nova within the last 12 months, you can start using Nova 4.0 right away with a free license that we’ve already added to your account. This license includes one year of updates before renewal is required.

**Comment by mertasan** [comment]
@llaski 

Ready for merge.

screenshot 27

**Comment by llaski** [comment]
@mertasan UI looks a bit squished but will take your word and assume all the tests are passing for the supported versions of PHP and nova 4. If there are issues will let someone else open an issue on it. 

For reference I last bought my license in 2018 I've actually been good for the first 3 major versions with it, this is actually the first one that I can't use with it. Wouldn't expect to have had last so long, but will get around to upgrading it at some point. Thanks for your contribution!

**Comment by mertasan** [comment]
Thanks! I have sent you an email.

**Pull request merged**
